# Generated by Django 2.0.8 on 2019-02-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
      migrations.RenameModel('Post', 'Quote')
    ]
