# Generated by Django 2.0.8 on 2019-02-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20190213_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_source',
            field=models.CharField(default='Source Unknown', help_text='Who said or wrote this quotation?', max_length=300),
        ),
    ]
